apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: kubadz/udagram-api-feed:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: aws-credentials
          mountPath: /root/.aws
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
      volumes:
      - name: aws-credentials
        secret:
          secretName: aws-secret